name: Package Stream Pack

on:
  push:
    branches:
      - useful_file
      - master
  pull_request:
    branches:
      - useful_file
      - master
  workflow_dispatch:

jobs:
  update_and_compress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout master branch
      uses: actions/checkout@v3
      with:
        ref: master

        
    - name: Create static directory
      run: mkdir -p static

    - name: Move master files to static directory
      run: |
        shopt -s dotglob
        mv !(static) static/

    - name: Pull useful_file branch
      run: |
        git fetch origin useful_file
        git checkout origin/useful_file -- .


    - name: Compress files with high compression
      run: |
        tar -czf static_files.tar.gz --use-compress-program=pigz static/

    - name: Upload the compressed file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: static_files
        path: static_files.tar.gz
