name: 打直播包

on:
  push:
    branches:
      - useful_file
      - master
  pull_request:
    branches:
      - useful_file
      - master
  workflow_dispatch:

jobs:
  update_and_compress:
    runs-on: ubuntu-latest

    steps:
    - name: 签出代码所在的master分支
      uses: actions/checkout@v3
      with:
        ref: master

        
    - name: 创建tosu需要的static目录
      run: mkdir -p static

    - name: 将master分支代码移到static目录
      run: |
        shopt -s extglob
        cp -af !(static) static/
        rm -rf !(static*)

    - name: 签出tosu/gosu/说明文件等所在的useful_file分支
      uses: actions/checkout@v3
      with:
        ref: useful_file


    - name: 打压缩包
      run: |
        zip -r9 static_files.zip ./

    - name: 重命名文件并上传
      run: |
        FILE_NAME="mp5-stream-overlay_$(date +'%Y-%m-%d').zip"
        mv static_files.zip $FILE_NAME
      uses: actions/upload-artifact@v3
      with:
        name: $FILE_NAME
        path: $FILE_NAME
