name: 打直播包

on:
  push:
    branches:
      - master
      - pack_without_useful_files
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  update_and_compress:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout files
      uses: actions/checkout@v3
      with:
        ref: ${{ github.ref_name }}
    
    - name: Create dist folder
      run: mkdir -p dist
        
    - name: Create static folder used by tosu
      run: mkdir -p dist/static

    - name: Move files
      run: |
        shopt -s extglob
        cp -af !(dist) dist/static/
        mv dist/static/*.json dist/

    - name: Download tosu release
      uses: wei/wget@v1
      with:
        args: -O tosu.zip https://github.com/tosuapp/tosu/releases/download/v3.6.0/tosu-windows-v3.6.0.zip
    
    - name: Extract tosu
      run: unzip tosu.zip -d dist/
    
    - name: Write configuration file
      run: |
        echo "ENABLE_AUTOUPDATE=false\nSTATIC_FOLDER_PATH=./static" > dist/tsosu.env

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mp5_stream_overlay_${{ github.ref_name }}_${{ github.sha }}
        path: dist
